# Java JDK

- apt_key: keyserver=keyserver.ubuntu.com id=7B2C3B0889BF5709A105D03AC2518248EEA14886

- apt_repository: repo='ppa:webupd8team/java'

- apt: update_cache=yes upgrade=yes cache_valid_time=3600

- name: accept oracle license
  debconf: name='oracle-java7-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- apt: name=oracle-java7-installer

# ElasticSearch

- apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch

- apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.3/debian stable main' state=present

- apt: name=elasticsearch

- command: /usr/share/elasticsearch/bin/plugin -i elasticsearch/marvel/latest
    creates=/usr/share/elasticsearch/plugins/marvel

- command: /usr/share/elasticsearch/bin/plugin -i elasticsearch/elasticsearch-cloud-aws/2.3.0
    creates=/usr/share/elasticsearch/plugins/cloud-aws

- lineinfile: 'dest=/etc/init.d/elasticsearch line="ES_HEAP_SIZE={{es_heap_size}}" regexp="^#?ES_HEAP_SIZE="'
  notify:
  - restart elasticsearch

- template: src=config.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml
  notify:
  - restart elasticsearch
